TOOL_HDELK = "hdelk"
TOOL_D3HW = "d3hw"

NET_SRC = "net_src"
NET_DST = "net_dst"
NET_SRCR = "net_srcr"
NET_DSTR = "net_dstr"
RNDR = "_renderer_"
A_FILEPATH = "_filepath_"
A_LOCALPATH = "_localpath_"
A_MISSING = "_missing_"

COPY_KEYS = (A_FILEPATH, A_LOCALPATH)
COMMON_KEYS = ("source", "merge")
COMMON_ALLOWED = {A_FILEPATH: None, A_MISSING: None, **{k: None for k in COMMON_KEYS}}
COMMON_REMAP = {
    A_FILEPATH: (RNDR, A_FILEPATH),
    A_LOCALPATH: (RNDR, A_LOCALPATH),
    A_MISSING: (RNDR, A_MISSING),
}

YAML_UNIT_KEYS = ("io", "generics", "units", "nets", "display", "attributes") + COMMON_KEYS
"""
Fields that are expected to be in Unit's definitions
Any other fields in definition would rise error                                     # TODO: it's not that right now
Any other fields in unit's instance would be transferred into 'attributes'
"""

YAML_UNIT_ALLOWED = {
    A_LOCALPATH: None,  # NOTE: this attribute is generated by tool for every unit
    **COMMON_ALLOWED,
    "io": None,
    "generics": None,
    "units": None,
    "nets": None,
    "display": None,
    "attributes": None,
    "operators": None,
}

YAML_UNIT_ATTRIBUTES_ALLOWED = {
    **COMMON_ALLOWED,
    "type": None,
    "d3hw_name": None,
    "kind": None,
    "color": None,
    "highlight": None,
    "text": None,
    "class": None,
    "style": None,
    "props": None,
    "hide": (None, True, False),    # TODO: list with rendering tools in which UNIT should be hidden
    "show": None,                   # TODO: list with rendering tools in which UNIT should be shown
    "hideNC": (None, True, False),  # TODO: list with rendering tools in which NC PINS should be hidden
}

YAML_UNIT_INSTANCE_ALLOWED = {
    **COMMON_ALLOWED,
    "unit": None,
    "name": None,
    "generics": None,
    "nets": None,
    "operators": None,
    # "display": None,  # TODO: support display per instance
    **YAML_UNIT_ATTRIBUTES_ALLOWED
}

YAML_UNIT_ATTRIBUTES_REMAP = {
    TOOL_HDELK: {
        **COMMON_REMAP,
        "type": ("type", ),
        "name": (("label", ), (RNDR, "name"), ),
        "color": ("color", ),
        "highlight": ("highlight", ),
        "text": (RNDR, "unit_text"),
        "hide": (RNDR, "unit_hide"),
        "show": (RNDR, "unit_show"),
        "hideNC": (RNDR, "hideNC"),
        # TODO: there is something equal to external port
    },
    TOOL_D3HW: {
        **COMMON_REMAP,
        "name": (RNDR, "name"),
        "type": (RNDR, "type"),
        "d3hw_name": ("hwMeta", "name"),
        "kind": ("hwMeta", "cls"),
        "color": (RNDR, "color"),
        "highlight": (RNDR, "highlight"),
        "text": ("hwMeta", "bodyText"),
        "class": ("hwMeta", "cssClass"),
        "style": ("hwMeta", "cssStyle"),
        "props": ("properties", ),
        "hide": (RNDR, "unit_hide"),
        "show": (RNDR, "unit_show"),
        "hideNC": (RNDR, "pins_hideNC"),
    },
}

UNIT_DEFAULTS = {
    TOOL_HDELK: {
    },
    TOOL_D3HW: {
        "hwMeta": {
            "cls": None,
            "children": [],
        },
        "properties": {
            "org.eclipse.elk.portConstraints": "FIXED_ORDER",
            "org.eclipse.elk.layered.mergeEdges": 1,
        },
        "ports": [],
    }
}

YAML_IO_KEYS = tuple() + COMMON_KEYS

YAML_IO_ALLOWED = {
    **COMMON_ALLOWED,
    "name": None,
    "dir": (None, "in", "out"),
    "side": (None, "east", "west", "north", "south"),
    "color": None,
    "highlight": None,
    "type": None,                       # TODO: typing can be used for compatibility checks and RTL code generation
    "bus": None,
    "clk": (None, True, False),
    "gate": (None, True, False),
    "inv": (None, True, False),
    "hide": (None, True, False),        # TODO: list with rendering tools in which PIN should be hidden
    "show": None,                       # TODO: list with rendering tools in which UNIT should be shown
    "autohide": (None, True, False),    # TODO: list with rendering tools in which PIN should be automatically hidden
    "order": None,
    "class": None,
    "style": None,
    "connectedAsParent": (None, True, False),
    "children": None,
    A_FILEPATH: None,  # NOTE: this attribute is generated by tool when data is loaded from file
}

YAML_IO_REMAP = {
    TOOL_HDELK: {
        **COMMON_REMAP,
        "name": (("label", ), (RNDR, "name"), ),
        "dir": (RNDR, "pin_dir"),
        "side": (RNDR, "pin_side"),
        "color": ("color",),
        "highlight": ("highlight",),
        "type": (RNDR, "pin_type"),
        "bus": (RNDR, "pin_bus"),
        "clk": (RNDR, "pin_clk"),
        "gate": (RNDR, "pin_gate"),
        "inv": (RNDR, "pin_inv"),
        "hide": (RNDR, "pin_hide"),
        "show": (RNDR, "pin_show"),
        "autohide": (RNDR, "pin_autohide"),
    },
    TOOL_D3HW: {
        **COMMON_REMAP,
        "name": (("hwMeta", "name"), (RNDR, "name"), ),
        "dir": ("direction", ),
        "side": ("properties", "side"),
        "color": (RNDR, "color"),
        "highlight": (RNDR, "highlight"),
        "type": (RNDR, "pin_type"),
        "bus": (RNDR, "pin_bus"),
        "clk": (RNDR, "pin_clk"),
        "gate": (RNDR, "pin_gate"),
        "inv": (RNDR, "pin_inv"),
        "hide": (RNDR, "pin_hide"),
        "show": (RNDR, "pin_show"),
        "autohide": (RNDR, "pin_autohide"),
        "order": ("properties", "index"),
        "class": ("hwMeta", "cssClass"),
        "style": ("hwMeta", "cssStyle"),
        "connectedAsParent": ("hwMeta", "connectedAsParent"),
    }
}

IO_DEFAULTS = {
    TOOL_HDELK: {
    },
    TOOL_D3HW: {
        "hwMeta": {
            # "level": 0,  # TODO: WTF? not in docs but this were in examples
        },
        "connectedAsParent": False,
        "properties": {},
    }
}


YAML_NET_KEYS = tuple() + COMMON_KEYS

YAML_NET_ALLOWED = {
    **COMMON_ALLOWED,
    "src": None,
    "dst": None,
    "srcr": None,
    "dstr": None,
    "name": None,
    "text": None,
    "bus": None,
    "color": None,
    "highlight": None,
    "reverse": None,
    "hide": (None, True, False),    # TODO: list with rendering tools in which NET should be hidden
    "show": None,                   # TODO: list with rendering tools in which UNIT should be shown
    "class": None,
    "style": None,
    A_FILEPATH: None,  # NOTE: this attribute is generated by tool when data is loaded from file
}

YAML_NET_REMAP = {
    TOOL_HDELK: {
        **COMMON_REMAP,
        "src": (RNDR, NET_SRC),
        "dst": (RNDR, NET_DST),
        "srcr": (RNDR, NET_SRCR),
        "dstr": (RNDR, NET_DSTR),
        "name": (("label", ), (RNDR, "name"),),
        "text": (RNDR, "net_text"),
        "bus": ("bus", ),
        "color": ("color", ),
        "highlight": ("highlight", ),
        "reverse": ("reverse", ),
        "hide": (RNDR, "net_hide"),
        "show": (RNDR, "unit_show"),
    },
    TOOL_D3HW: {
        **COMMON_REMAP,
        "src": (RNDR, NET_SRC),
        "dst": (RNDR, NET_DST),
        "srcr": (RNDR, NET_SRCR),
        "dstr": (RNDR, NET_DSTR),
        "name": (("hwMeta", "name"), (RNDR, "name"),),
        "text": (RNDR, "net_text"),
        "bus": (RNDR, "net_bus"),
        "color": (RNDR, "color"),
        "highlight": (RNDR, "highlight"),
        "hide": (RNDR, "net_hide"),
        "show": (RNDR, "unit_show"),
        "class": ("hwMeta", "cssClass"),
        "style": ("hwMeta", "cssStyle"),
    }
}

NET_DEFAULTS = {
    TOOL_HDELK: {
    },
    TOOL_D3HW: {
        "hwMeta": {
            "name": None,
        },
    }
}

VIEW_NONE = "none"
VIEW_SYMBOL = "symbol"
VIEW_FULL = "full"
VIEW_NESTED = "nested"

PIN_INV_PREFIX = None
PIN_INV_SUFFIX = "#"
PIN_GATE_HIGH = u"\u2A05"
PIN_GATE_LOW = u"\u2A06"
PIN_CLK_RISE = u"\u25B7"  # Alternatives: "/" u"\u2191"  u"\u25B7"  u"\u2B06"  u"\u2197"  u"\u21D1"
PIN_CLK_FALL = u"\u25B6"  # Alternatives: "\\" u"\u2193"  u"\u25B6"  u"\u2B07"  u"\u2198"  u"\u21D3"

# TODO: RENDER_OPTIONS to VIEW options (i.e do it per scope)
RENDER_ADD_MISSING_PORTS = 1            # Adds missing ports onto schematic (those that are mensionned on nets)
RENDER_ADD_MISSING_UNITS = 2            # Adds missing units onto schematic (those that are mensionned on nets)
RENDER_HIGHLIGHT_MISSING_PORTS = 9      # Highlights missing
RENDER_HIGHLIGHT_MISSING_UNITS = 10     # Highlights missing
RENDER_COLLAPSE_INNER = 3               # Collapses multiple connections between two units within scope into single
RENDER_COLLAPSE_OUTER = 4               # Collapses multiple connections between two units (one within scope and another in outer scope) into single
RENDER_COLLAPSE_NESTED = 5              # Collapses multiple connections between two units (one within scope and another in subscope) into single
RENDER_COLLAPSE_INNER_ONE_PORT = 6      # Collapses all connections of this type into one point on unit
RENDER_COLLAPSE_OUTER_ONE_PORT = 7      # Collapses all connections of this type into one point on unit
RENDER_COLLAPSE_NESTED_ONE_PORT = 8     # Collapses all connections of this type into one point on unit
